version: '3'
services:
  web:
    build: ./container/web/.
    depends_on: 
      - php
      - db
    ports:
      - '80:80'
    volumes:
      - site-data:/var/www/html
      - ./container/web/nginx.conf:/etc/nginx/conf.d/default.conf
  
  composer:
    build: ./container/composer/.
    depends_on:
        - db
    volumes:
        - site-data:/site
    environment: 
      TYPO3_INSTALL_DB_USER: ${DB_USER}
      TYPO3_INSTALL_DB_PASSWORD: ${DB_PASS}
      TYPO3_INSTALL_DB_HOST: ${DB_HOST}
      TYPO3_INSTALL_DB_PORT: ${DB_PORT}
      TYPO3_INSTALL_DB_USE_EXISTING: ${DB_USE_EXISTING}
      TYPO3_INSTALL_DB_DBNAME: ${DB_NAME}
      TYPO3_INSTALL_ADMIN_USER: ${TYPO3_USER}
      TYPO3_INSTALL_ADMIN_PASSWORD: ${TYPO3_PASS}
      TYPO3_INSTALL_SITE_NAME: ${TYPO3_SITE_NAME}
      COMPOSER_PROCESS_TIMEOUT: ${COMPOSER_TIMEOUT}
  
  php:
      build: ./container/php/.
      volumes:
        - site-data:/var/www/html
        - ./container/php/php.ini:/usr/local/etc/php/php.ini
        - ./container/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      environment: 
        TYPO3_CONTEXT: Development

  db:
      image: mysql:8.0.17
      command: mysqld --default-authentication-plugin=mysql_native_password
      volumes:
          - db-data:/var/lib/mysql
      environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

volumes:
  db-data:
  site-data: